ansible_host: 192.168.1.106
interface_details:
  - name: GigabitEthernet2
    desc: Connected to CSR1
    ip_address: 20.20.20.2
    mask: 255.255.255.0
  - name: GigabitEthernet3
    desc: Connected to CSR2
    ip_address: 30.30.30.2
    mask: 255.255.255.0
  - name: GigabitEthernet4
    desc: Connected to WAN - faulty port
    ip_address: 40.40.40.2
    mask: 255.255.255.0
