 ansible_host: 192.168.1.105
 interface_details:
  - name: GigabitEthernet2
    desc: Connected to C8K1
    ip_address: 30.30.30.1
    mask: 255.255.255.0
  - name: GigabitEthernet3
    desc: Connected to CSR2
    ip_address: 50.50.50.2
    mask: 255.255.255.0
  - name: GigabitEthernet4
    desc: Connected to NXOS2
    ip_address: 70.70.70.1
    mask: 255.255.255.0
