---
  - name: Demo on Jinja2 template - Include
    hosts: vIOS
    gather_facts: false
    tasks:
      - name: Generate full configuration
        template:
          src: full_config.j2
          dest: "{{playbook_dir}}/config_files/{{inventory_hostname}}_full_config.cfg"
